# Generated by Django 2.2.5 on 2019-10-16 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import repoApp.models.metricsRelated
import repoApp.models.testRelated


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidProject',
            fields=[
                ('project_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project_build_tool', models.CharField(blank=True, default='gradle', max_length=16)),
                ('project_desc', models.CharField(blank=True, default='', max_length=64)),
                ('project_location', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('app_package', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('app_description', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('app_flavor', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('app_build_type', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('app_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_project', to='repoApp.AndroidProject')),
            ],
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=64)),
                ('class_package', models.CharField(max_length=64)),
                ('class_language', models.CharField(default='java', max_length=32)),
                ('class_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_app', to='repoApp.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_serial_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('device_brand', models.CharField(max_length=32)),
                ('device_model', models.CharField(max_length=32)),
                ('device_ram', models.CharField(default=None, max_length=16, null=True)),
                ('device_cores', models.IntegerField(default=1)),
                ('device_max_cpu_freq', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_kernel_version', models.CharField(default=None, max_length=224, null=True)),
                ('state_os_version', models.CharField(default=None, max_length=16, null=True)),
                ('state_miui_version', models.CharField(default=None, max_length=16, null=True)),
                ('state_api_version', models.FloatField(default=None, null=True)),
                ('state_operator', models.CharField(default=None, max_length=128, null=True)),
                ('state_operator_country', models.CharField(default='PT', max_length=16, null=True)),
                ('state_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateOf', to='repoApp.Device')),
            ],
            options={
                'unique_together': {('state_device_id', 'state_kernel_version')},
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('method_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=255)),
                ('method_return', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('method_modifiers', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('method_args', models.CharField(default=None, max_length=256, null=True)),
                ('method_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classofmethod', to='repoApp.Class')),
            ],
            options={
                'unique_together': {('method_name', 'method_class', 'method_id')},
            },
        ),
        migrations.CreateModel(
            name='Profiler',
            fields=[
                ('profiler_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('profiler_type', enumfields.fields.EnumField(enum=repoApp.models.testRelated.ProfilerType, max_length=1)),
                ('profiler_version', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('study_authors', models.CharField(max_length=128)),
                ('study_publisher', models.CharField(max_length=64)),
                ('study_year', models.IntegerField()),
                ('study_isbn', models.CharField(max_length=64)),
                ('study_organization', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_app', to='repoApp.Application')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrientation',
            fields=[
                ('test_orientation_designation', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('test_results_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_results_unix_timestamp', models.IntegerField(default=1, unique=True)),
                ('test_results_seed', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('test_results_description', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('test_results_device_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testedOn', to='repoApp.DeviceState')),
                ('test_results_profiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiledOn', to='repoApp.Profiler')),
                ('test_results_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='repoApp.Test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_type', to='repoApp.TestOrientation'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_tool', to='repoApp.Tool'),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('metric_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[(repoApp.models.metricsRelated.MetricType('s'), 's'), (repoApp.models.metricsRelated.MetricType('d'), 'd'), (repoApp.models.metricsRelated.MetricType('h'), 'h')], max_length=1)),
                ('metric_category', models.CharField(choices=[(repoApp.models.metricsRelated.MetricCategory('a'), 'a'), (repoApp.models.metricsRelated.MetricCategory('p'), 'p'), (repoApp.models.metricsRelated.MetricCategory('h'), 'h'), (repoApp.models.metricsRelated.MetricCategory('m'), 'm'), (repoApp.models.metricsRelated.MetricCategory('o'), 'o')], max_length=1)),
                ('metric_related_study', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accordingto', to='repoApp.Study')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(default='', max_length=384)),
                ('coeficient', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='repoApp.Metric')),
                ('test_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='repoApp.TestResults')),
            ],
            options={
                'unique_together': {('test_results', 'metric')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('test_application', 'test_tool', 'test_orientation')},
        ),
        migrations.CreateModel(
            name='MethodMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_value_text', models.CharField(default='', max_length=384)),
                ('mm_coeficient', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('mm_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmmethod', to='repoApp.Method')),
                ('mm_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmmethodHasMetric', to='repoApp.Metric')),
                ('mm_test_result', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmmtest', to='repoApp.TestResults')),
            ],
            options={
                'unique_together': {('mm_method', 'mm_metric', 'mm_value_text')},
            },
        ),
        migrations.CreateModel(
            name='MethodInvoked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_invoked', models.IntegerField(default=1)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='repoApp.Method')),
                ('test_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='repoApp.TestResults')),
            ],
            options={
                'unique_together': {('method', 'test_results')},
            },
        ),
        migrations.CreateModel(
            name='ImportClass',
            fields=[
                ('import_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('import_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classofimport', to='repoApp.Class')),
            ],
            options={
                'unique_together': {('import_name', 'import_class')},
            },
        ),
        migrations.CreateModel(
            name='ClassMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_value_text', models.CharField(default='', max_length=512)),
                ('cm_coeficient', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('cm_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmetric', to='repoApp.Class')),
                ('cm_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasMetric', to='repoApp.Metric')),
                ('cm_test_result', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmtest', to='repoApp.TestResults')),
            ],
            options={
                'unique_together': {('cm_class', 'cm_metric', 'cm_value_text')},
            },
        ),
        migrations.CreateModel(
            name='AppMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_value_text', models.CharField(default='', max_length=384)),
                ('am_coeficient', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('am_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aapp', to='repoApp.Application')),
                ('am_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahasMetric', to='repoApp.Metric')),
                ('am_test_result', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ammtest', to='repoApp.TestResults')),
            ],
            options={
                'unique_together': {('am_app', 'am_metric', 'am_value_text')},
            },
        ),
        migrations.CreateModel(
            name='AppHasPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasapp', to='repoApp.Application')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haspermission', to='repoApp.AppPermission')),
            ],
            options={
                'unique_together': {('application', 'permission')},
            },
        ),
    ]
