# Generated by Django 2.2.5 on 2019-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidproject',
            name='project_desc',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='androidproject',
            name='project_location',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
