# Generated by Django 2.1 on 2018-09-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportClass',
            fields=[
                ('import_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classhasimport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classhasimport',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classhasimport',
            name='class_imp',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_acc_modifier',
            field=models.CharField(default='', max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='ClassHasImport',
        ),
        migrations.DeleteModel(
            name='Import',
        ),
        migrations.AddField(
            model_name='importclass',
            name='import_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classofimport', to='repoApp.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='importclass',
            unique_together={('import_name', 'import_class')},
        ),
    ]
