# Generated by Django 2.1 on 2018-09-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_description',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_acc_modifier',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_non_acc_mod',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_superclass',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
