# Generated by Django 2.1 on 2018-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0002_auto_20180905_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_acc_modifier',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_non_acc_mod',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_superclass',
            field=models.CharField(default='', max_length=64),
        ),
    ]
