# Generated by Django 2.1 on 2018-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0003_auto_20180911_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidproject',
            name='project_desc',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
