# Generated by Django 2.1 on 2018-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0003_auto_20180905_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_acc_modifier',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_implemented_ifaces',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_non_acc_mod',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_superclass',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
