# Generated by Django 2.1 on 2018-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0004_auto_20180911_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidproject',
            name='project_build_tool',
            field=models.CharField(blank=True, default='gradle', max_length=16),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_build_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_acc_modifier',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_non_acc_mod',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
